### PR TITLE
new pop cap features and removal of shr_cal_mod uses

### PR DESCRIPTION
**Pull request by mvertens**
new pop cap features and removal of shr_cal_mod uses

This PR does several things:

- new calendar changes:
    now set default calendar in ensemble_driver.F90
    removed uses of shr_cal_mod from mediator code
- new nuopc pop cap support:
   added new logic for flds_i2o_per_cat and fix problems with Si_ifrac_01 and Fioi_swpen_ifrac_01 in nuopc/dice_comp_mod.F90
   added Faxa_nhx and Faxa_noy to fd.yaml
   fixed problems with Foxx_swnet and Si_ifrac_n for input to pop
- pio:
set default PIO_REARRANGER to box_rearranger
- other cleanup
   removed uses of shr_string_mod from mediator code
   removed references to wind gust in med_phases_aofluxes_mod
- meshes:
   add TL319 mesh in config_grid.xml
   add new domain mesh for JRA025
- testing:
   add a new argument for create_test (--xml_driver) that can now be set to nuopc
- bug fix in glc_comp_nuopc:
  following modification was made that will changes answers from baselines for X compsets
```
old:
  if (fldname == 'Sg_icemask' .or. 'fldname == Sg_icemask_coupled_fluxes' ....
new:
  if (fldname == 'Sg_icemask' .or.  fldname == 'Sg_icemask_coupled_fluxes' ....
```
- namelist_defininition_drv.xml
   removed e3sm attributes in namelist_definition_driver.xml
   added new support for flux_epbal config setting
   added new xml variable "ScalarFieldIdxValidGlcInput"

Test suite: testlist_drv.xml on cheyenne
Test baseline:  may10intel19
Test namelist changes: no
Test status: bit for bit 
   (except for 1 field in SMS_Vnuopc.f19_g17.X.cheyenne_intel and ERS_Vnuopc.f19_g17.X.cheyenne_intel - see above)
Fixes None
User interface changes?: no
Update gh-pages html (Y/N)?:n
Code review:

### CODE REVIEW

**Comment by rsdunlapiv** [comment]
@mvertens Can you please include the hashes of all the components?

**Comment by uturuncoglu** [comment]
@mvertens following tests are failed,

FAIL ERR_Vnuopc_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io COMPARE_base_rest
FAIL ERS_Vnuopc_Ld5.T62_g16.CMOM.cheyenne_intel COMPARE_base_rest
FAIL ERS_Vnuopc_Ld5.T62_g16.GMOM.cheyenne_intel COMPARE_base_rest
FAIL ERS_Vnuopc_Ln9.f19_g17.X.cheyenne_intel BASELINE may10intel19: DIFF
FAIL SMS_Vnuopc.f19_g17.X.cheyenne_intel BASELINE may10intel19: DIFF

I think that first three tests related with MOM is expected due to the problem in the MOM side and they were also failing when generating baselines. The last two one are also expected as it indicated in PR.

**Comment by mvertens** [comment]
That is correct. Thanks for verifying.

**Comment by mvertens** [comment]
Will do once I get to the hotel. Sorry about that.

**Comment by uturuncoglu** [comment]
I also tested fv3gfs application and the build is failing without following fix in mom interface 

https://github.com/ESCOMP/MOM_interface/commit/007dbe828cb82b732b11c1a98b9dfd721d729e06

noupc_cmeps_fv3 branch in MOM_interface also needs to include this particular fix and Externals.cfg must be updated accordingly. BTW, the app_cesm-cmeps is working without any problem after merge with PR because nuopc_cmeps branch already has this fix. The fv3gfs application is working without any problem after fix. So, i'll wait for @jedwards4b to marge this PR.

**Comment by uturuncoglu** [comment]
Sorry for the closing of PR. It was a unexpected mouse movement. I reopened it.

**Comment by rsdunlapiv** [comment]
@uturuncoglu Can we remove the noupc_cmeps_fv3 branch of MOM_interface so that we don't have to keep it in sync?  Since we merged all the fv3 stuff back, it seems like we could get rid of that branch.

**Comment by uturuncoglu** [comment]
@rsdunlapiv Do we need to point nuopc_cmeps after that?

**Comment by rsdunlapiv** [comment]
@uturuncoglu It looks like it should be this branch:
https://github.com/ESCOMP/MOM_interface/tree/nuopc_branch

**Review by uturuncoglu — APPROVED** [review]

**Pull request merged**
