### PR TITLE
Jedwards/addgptl

### PR DESCRIPTION
**Pull request by jedwards4b**
Adds some timers to nuopc driver and adds a smart compare tool for runconfig files. 

Test suite: by hand
Test baseline: 
Test namelist changes: 
Test status: bit for bit

Fixes 

User interface changes?: 

Update gh-pages html (Y/N)?:

Code review:

### CODE REVIEW

**Comment by rsdunlapiv** [comment]
@jedwards4b How do I turn on the timers and see the output?

**Comment by jedwards4b** [comment]
Timers are on by default and output goes into the timing subdirectory of the case.  However because I still have some key timers missing the timing summary file is still mostly empty.   Compare to an mct case and notice that until now the nuopc didn't create a timing directory at all.

**Comment by rsdunlapiv** [comment]
```
dunlap@cheyenne1:~/UFSCOMP.oct17/cime/scripts> qcmd -l walltime=04:00:00 -- ./create_test --xml-machine cheyenne --xml-testlist testlist_cmeps.xml --baseline-root /glade/scratch/dunlap/BASELINES --compare oct5
```

**Comment by rsdunlapiv** [comment]
@jedwards4b I got a bunch of baseline comparison failures against the oct5 baseline.  I doubt this is related to the timers so I must have something wrong.  Would you expect to need new baselines after the recent merge of CIME master back into nuopc-cmeps?

**Comment by jedwards4b** [comment]
Yes, I was just looking into this myself - some data model input files have changed.  I think that this is an expected difference and we need to create new baselines.   Here is the responsible PR https://github.com/ESMCI/cime/pull/2828

**Comment by rsdunlapiv** [comment]
Makes sense to me since the compsets with active CAM matched the baselines - so indeed does seem to be related to DATM input files.  I'll merge in this PR and then regenerate baselines.

**Comment by rsdunlapiv** [comment]
Also I did confirm creation of the timing directory with the NUOPC cases.

**Pull request merged**
