### PR TITLE
update esmf version and logging

### PR DESCRIPTION
**Pull request by jedwards4b**
This PR is mostly intended to test the travis-ci connection.  But it updates ESMF to use the new ESMF_LOGKIND_MULTI_ON_ERROR feature.   A future PR will allow us to tune this setting in cesm.runconfig

Test suite: scripts_regression_tests.py A_RunUnitTests B_CheckCode
Test baseline: 
Test namelist changes: 
Test status: bit for bit

Fixes 
User interface changes?: 

Update gh-pages html (Y/N)?:

Code review:

### CODE REVIEW

**Comment by rsdunlapiv** [comment]
Case dir: /glade/scratch/dunlap/SMS_Vmct_Ln5.ne16_ne16_mg17.QPC4.cheyenne_intel.cam-nuopc_cap.C.aug10update
    Errors were:
        Test 'SMS_Vmct_Ln5.ne16_ne16_mg17.QPC4.cheyenne_intel.cam-nuopc_cap' failed in phase 'SETUP' with exception 'ERROR: Fatal error in case.cmpgen_namelists: Setting resource.RLIMIT_STACK to -1 from (-1, -1)
        Creating component namelists
           Calling /gpfs/u/home/dunlap/UFSCOMP.aug9/components/cam//cime_config/buildnml
             ...calling cam buildcpp to set build time options
        CAM namelist copy: file1 /glade/scratch/dunlap/SMS_Vmct_Ln5.ne16_ne16_mg17.QPC4.cheyenne_intel.cam-nuopc_cap.C.aug10update/Buildconf/camconf/atm_in file2 /glade/scratch/dunlap/SMS_Vmct_Ln5.ne16_ne16_mg17.QPC4.cheyenne_intel.cam-nuopc_cap.C.aug10update/run/atm_in 
           Calling /gpfs/u/home/dunlap/UFSCOMP.aug9/cime/src/components/stub_comps/slnd/cime_config/buildnml
           Calling /gpfs/u/home/dunlap/UFSCOMP.aug9/cime/src/components/stub_comps/sice/cime_config/buildnml
           Calling /gpfs/u/home/dunlap/UFSCOMP.aug9/cime/src/components/data_comps/docn/cime_config/buildnml
           Calling /gpfs/u/home/dunlap/UFSCOMP.aug9/cime/src/components/stub_comps/srof/cime_config/buildnml
           Calling /gpfs/u/home/dunlap/UFSCOMP.aug9/cime/src/components/stub_comps/sglc/cime_config/buildnml
           Calling /gpfs/u/home/dunlap/UFSCOMP.aug9/cime/src/components/stub_comps/swav/cime_config/buildnml
           Calling /gpfs/u/home/dunlap/UFSCOMP.aug9/cime/src/components/stub_comps/sesp/cime_config/buildnml
           Calling /gpfs/u/home/dunlap/UFSCOMP.aug9/cime/src/drivers/mct/cime_config/buildnml
        Traceback (most recent call last):
          File "./case.cmpgen_namelists", line 61, in <module>
            _main_func(__doc__)
          File "./case.cmpgen_namelists", line 56, in _main_func
            success = case.case_cmpgen_namelists(compare, generate, compare_name, generate_name, baseline_root)
          File "/gpfs/u/home/dunlap/UFSCOMP.aug9/cime/scripts/Tools/../../scripts/lib/CIME/case/case_cmpgen_namelists.py", line 101, in case_cmpgen_namelists
            self.create_namelists()
          File "/gpfs/u/home/dunlap/UFSCOMP.aug9/cime/scripts/Tools/../../scripts/lib/CIME/case/preview_namelists.py", line 88, in create_namelists
            run_sub_or_cmd(cmd, (caseroot), "buildnml", (self, caseroot, compname), case=self)
          File "/gpfs/u/home/dunlap/UFSCOMP.aug9/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 345, in run_sub_or_cmd
            getattr(mod, subname)(*subargs)
          File "/gpfs/u/home/dunlap/UFSCOMP.aug9/cime/src/drivers/mct/cime_config/buildnml", line 392, in buildnml
            _create_component_modelio_namelists(case, files)
          File "/gpfs/u/home/dunlap/UFSCOMP.aug9/cime/src/drivers/mct/cime_config/buildnml", line 298, in _create_component_modelio_namelists
            definition_dir = os.path.dirname(files.get_value("NAMELIST_DEFINITION_FILE", attribute={"component":"drv"}, comp_interface="mct"))
        TypeError: get_value() got an unexpected keyword argument 'comp_interface''
          File "/gpfs/u/home/dunlap/UFSCOMP.aug9/cime/scripts/Tools/../../scripts/lib/CIME/test_scheduler.py", line 685, in _run_catch_exceptions
            return run(test)
          File "/gpfs/u/home/dunlap/UFSCOMP.aug9/cime/scripts/Tools/../../scripts/lib/CIME/test_scheduler.py", line 650, in _setup_phase
            expect(cmdstat in [0, TESTS_FAILED_ERR_CODE], "Fatal error in case.cmpgen_namelists: {}".format(output))
          File "/gpfs/u/home/dunlap/UFSCOMP.aug9/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 130, in expect
            raise exc_type(msg)

**Comment by rsdunlapiv** [comment]
Got a bit further this time:

Finished MODEL_BUILD for test SMS_Vnuopc.f19_g16.X.cheyenne_intel in 46.830443 seconds (FAIL). [COMPLETED 1 of 36]
    Case dir: /glade/scratch/dunlap/SMS_Vnuopc.f19_g16.X.cheyenne_intel.C.aug10updateB
    Errors were:
        Building test for SMS in directory /glade2/scratch2/dunlap/SMS_Vnuopc.f19_g16.X.cheyenne_intel.C.aug10updateB
        /gpfs/u/home/dunlap/UFSCOMP.aug9/cime/src/drivers/nuopc/cime_driver/esmApp.F90(24): error #6404: This name does not have a type, and must have an explicit type.   [ESMF_LOGKIND_MULTI_ON_ERROR]
        
        ERROR: BUILD FAIL: buildexe failed, cat /glade/scratch/dunlap/SMS_Vnuopc.f19_g16.X.cheyenne_intel.C.aug10updateB/bld/cesm.bldlog.180810-155220

**Comment by rsdunlapiv** [comment]
ESMF_LOGKIND_MULTI_ON_ERROR is missing the the esmApp.F90 use statements.  Or we always need to run with DEBUG set.  How do I set that?

#ifdef DEBUG
  call ESMF_Initialize(logkindflag=ESMF_LOGKIND_MULTI, logappendflag=.false., &
    defaultCalkind=ESMF_CALKIND_GREGORIAN, ioUnitLBound=5001, ioUnitUBound=5101, rc=rc)
#else
  call ESMF_Initialize(logkindflag=ESMF_LOGKIND_MULTI_ON_ERROR, logappendflag=.false., &
    defaultCalkind=ESMF_CALKIND_GREGORIAN, ioUnitLBound=5001, ioUnitUBound=5101, rc=rc)
#endif

**Comment by jedwards4b** [comment]
FIxed,  my plan is to implement setting this from cesm.runconfig in a (near) future PR.

**Comment by rsdunlapiv** [comment]
Kicked off another test:
dunlap@cheyenne5:~/UFSCOMP.aug9/cime/scripts/tests> qcmd -l walltime=4:00:00 -- ./create_test --xml-testlist ./testlist_cmeps.xml --xml-machine cheyenne --xml-category prealpha --test-id aug10updateC --walltime 2:00:00 --compare restart_cime5.6.8 --baseline-root /glade/scratch/jedwards/BASELINES
Submitting command to PBS using account P93300606:
    ./create_test --xml-testlist ./testlist_cmeps.xml --xml-machine cheyenne --xml-category prealpha --test-id aug10updateC --walltime 2:00:00 --compare restart_cime5.6.8 --baseline-root /glade/scratch/jedwards/BASELINES

Requested custom PBS options:
    -l walltime=4:00:00 

Waiting for job 1608956.chadmin1 to start ...

**Comment by rsdunlapiv** [comment]
Almost, but still failing.

The symbol ESMF_LOGKIND_MULTI_ON_ERROR should come from ESMF not ESM:

use ESM,  only: esmSS => SetServices, ESMF_LOGKIND_MULTI_ON_ERROR

**Comment by jedwards4b** [comment]
sorry, fixed now

**Comment by rsdunlapiv** [comment]
New failures:

dunlap@cheyenne5:/glade/scratch/dunlap/SMS_Vnuopc_Ld1.T31_g37_rx1.A.cheyenne_intel.C.aug13update/run> more PET00.ESMF_LogFile 
20180813 103301.527 ERROR            PET00 esm.F90:194 Not found  - Passing error in return code
20180813 103301.527 ERROR            PET00 esm:src/addon/NUOPC/src/NUOPC_Driver.F90:463 Not found  - Passing error in return code
20180813 103301.527 ERROR            PET00 esm:src/addon/NUOPC/src/NUOPC_Driver.F90:329 Not found  - Passing error in return code
20180813 103301.527 ERROR            PET00 esmApp.F90:67 Not found  - Passing error in return code
20180813 103301.527 INFO             PET00 Finalizing ESMF

**Comment by jedwards4b** [comment]
superceeded by #35

**Pull request closed without merging**
