### PR TITLE
Jedwards/fixalarms

### PR DESCRIPTION
**Pull request by jedwards4b**
Causes med_profile timer information to be written to the log on first and last step regardless of the length of the run or alignment with alarms.   Puts the code to set the stop_alarm into share code for components.

Test suite: ./create_test --xml-testlist ./testlist_cmeps.xml --xml-machine cheyenne --xml-category prealpha --walltime 00:30:00 --compare nov15 --baseline-root /glade/scratch/dunlap/BASELINES 
Test baseline: nov15
Test namelist changes: 
Test status: bit for bit

Fixes 

User interface changes?: 

Update gh-pages html (Y/N)?:

Code review: 

components used
cam: 90250
cice: 004c933
clm: 88c6836
mom cap:7ff64af
  MOM: 4a5a5d87
mosart: d8210ddb

### CODE REVIEW

**Comment by jedwards4b** [comment]
travis-ci is failing due to some new tests in pylint 3 - I will fix on next PR.

**Comment by jedwards4b** [comment]
@rsdunlapiv you may want to generate new baselines with this so that the next NLCOMP will pass

**Comment by rsdunlapiv** [comment]
@jedwards4b Can you please confirm your cice and clm hashes - I can't seem to find these:

cice: 004c933
clm: 88c6836

**Comment by jedwards4b** [comment]
I forgot to push them - should be available now.

**Comment by rsdunlapiv** [comment]
```
dunlap@cheyenne6:~/UFSCOMP.nov13/cime> qcmd -l walltime=04:00:00 -- ./create_test --xml-machine cheyenne --xml-testlist testlist_cmeps.xml --baseline-root /glade/scratch/dunlap/BASELINES --compare nov15 --generate nov28
```

**Comment by rsdunlapiv** [comment]
Failures are as expected:

```
dunlap@cheyenne2:/glade/scratch/dunlap> ./cs.status.20181128_104321_aavb79 | grep "FAIL "
    FAIL ERR_Vmct_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io COMPARE_base_rest
    FAIL ERR_Vnuopc_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io NLCOMP
    FAIL ERS_Vmct_Ld5.T62_g16.CMOM.cheyenne_intel.mom-nuopc_cap COMPARE_base_rest
    FAIL ERS_Vmct_Ld5.T62_g16.GMOM.cheyenne_intel.mom-nuopc_cap COMPARE_base_rest
    FAIL ERS_Vnuopc_Ld5.T62_g16.CMOM.cheyenne_intel.mom-nuopc_cap NLCOMP
    FAIL ERS_Vnuopc_Ld5.T62_g16.GMOM.cheyenne_intel.mom-nuopc_cap NLCOMP
    FAIL ERS_Vnuopc_Ld5.T62_g37.DTEST.cheyenne_intel.cice-nuopc_cap NLCOMP
    FAIL ERS_Vnuopc_Ln5.f19_g17.F2000Nuopc.cheyenne_intel.cam-nuopc_cap NLCOMP
    FAIL ERS_Vnuopc_Ln5.f45_f45_mg37.I2000Clm50SpNuopc.cheyenne_intel.clm-nuopc_cap NLCOMP
    FAIL ERS_Vnuopc_Ln5.ne16_ne16_mg17.QPC4.cheyenne_intel.cam-nuopc_cap NLCOMP
    FAIL ERS_Vnuopc_Ln9.f19_g17.X.cheyenne_intel NLCOMP
    FAIL ERS_Vnuopc_Ln9_N3.f19_g17_rx1.A.cheyenne_intel NLCOMP
    FAIL SMS_Vnuopc.f19_g17.X.cheyenne_intel NLCOMP
    FAIL SMS_Vnuopc_Ld1_N3.f19_g17_rx1.A.cheyenne_intel NLCOMP
    FAIL SMS_Vnuopc_Ld2.ww3a.ADWAV.cheyenne_intel NLCOMP
    FAIL SMS_Vnuopc_Ld3.f09_f09_mg17.A1850DLND.cheyenne_intel NLCOMP
    FAIL SMS_Vnuopc_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io NLCOMP
    FAIL SMS_Vnuopc_Ld5.T62_g16.CMOM.cheyenne_intel.mom-nuopc_cap NLCOMP
    FAIL SMS_Vnuopc_Ld5.T62_g16.GMOM.cheyenne_intel.mom-nuopc_cap NLCOMP
    FAIL SMS_Vnuopc_Ld5.T62_g37.DTEST.cheyenne_intel.cice-nuopc_cap NLCOMP
    FAIL SMS_Vnuopc_Ln5.f19_g17.F2000Nuopc.cheyenne_intel.cam-nuopc_cap NLCOMP
    FAIL SMS_Vnuopc_Ln5.f45_f45_mg37.I2000Clm50SpNuopc.cheyenne_intel.clm-nuopc_cap NLCOMP
    FAIL SMS_Vnuopc_Ln5.ne16_ne16_mg17.QPC4.cheyenne_intel.cam-nuopc_cap NLCOMP
```

**Pull request merged**
