### PR TITLE
Jedwards/merge cmeps

### PR DESCRIPTION
**Pull request by jedwards4b**
This is the merge of the nuopc development branch to cime master.  Baselines will be different for many mct cases and match cime master with the exceptions noted below.  

Test suite: scripts_regression_tests.py (all pass)
create_test --xml-testlist ./testlist_cmeps.xml --xml-machine cheyenne --xml-category prealpha --compare sept19 --baseline-root /glade/scratch/dunlap/BASELINES
I also ran cime_developer and compared baselines against cime master
All tests pass with the exception of
FAIL ERI.f09_g16.X.cheyenne_intel BASELINE cimemaster0921: DIFF
FAIL ERIO.f09_g16.X.cheyenne_intel BASELINE cimemaster0921: DIFF
FAIL IRT_N2.f19_g16_rx1.A.cheyenne_intel BASELINE cimemaster0921:
The x cases are inconsequential and the A case was failing on master and works on the branch.

Test baseline: cime master 3effd6
Test namelist changes:
Test status: bit for bit
Fixes

User interface changes?:

Update gh-pages html (Y/N)?:

Code review:

### CODE REVIEW

**Comment by rsdunlapiv** [comment]
```
dunlap@cheyenne1:~/UFSCOMP.sept24/cime/scripts> qcmd -l walltime=04:00:00 -- ./create_test --xml-machine cheyenne --xml-testlist testlist_cmeps.xml --baseline-root /glade/scratch/dunlap/BASELINES --compare sept19 --generate sept24 --test-id sept24
```

**Comment by rsdunlapiv** [comment]
Build error with CLM.  Please confirm the hash for CLM (and other components.)

```
cat /glade/scratch/dunlap/SMS_Vmct_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io.GC.sept24/bld/lnd.bldlog.180924-094353

/gpfs/u/home/dunlap/UFSCOMP.sept24/components/clm/src/cpl/mct/lnd_comp_mct.F90(683): error #6285: There is no matching specific subroutine for this generic subroutine call.   [SEQ_INFODATA_GETDATA]
    call seq_infodata_GetData(infodata, lnd_resume=lnd_resume )
---------^
compilation aborted for /gpfs/u/home/dunlap/UFSCOMP.sept24/components/clm/src/cpl/mct/lnd_comp_mct.F90 (code 1)
gmake: *** [lnd_comp_mct.o] Error 1

ERROR: Command gmake complib -j 8 MODEL=clm COMPLIB=/glade/scratch/dunlap/SMS_Vmct_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io.GC.sept24/bld/intel/mpt/nodebug/nothreads/mct/esmf/lib/libclm.a -f /glade/scratch/dunlap/SMS_Vmct_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io.GC.sept24/Tools/Makefile MACFILE=/glade/scratch/dunlap/SMS_Vmct_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io.GC.sept24/Macros.cheyenne  failed with rc=2
```

**Comment by jedwards4b** [comment]
cam: nuopc_cap_n23_cam6_0_002
cice: d772fff
clm: ce1e3709
mom_interface: 4b1b8b0
MOM: 9733d7d

**Comment by rsdunlapiv** [comment]
Restarted tests with right hashes:
```
dunlap@cheyenne1:~/UFSCOMP.sept24/cime/scripts> qcmd -l walltime=04:00:00 -- ./create_test --xml-machine cheyenne --xml-testlist testlist_cmeps.xml --baseline-root /glade/scratch/dunlap/BASELINES --compare sept19 --generate sept24 --test-id sept24
```

**Comment by rsdunlapiv** [comment]
@jedwards4b, xice mct build error:

```
    Case dir: /glade/scratch/dunlap/SMS_Vmct.f19_g16.X.cheyenne_intel.GC.sept24
    Errors were:
        Building test for SMS in directory /gpfs/fs1/scratch/dunlap/SMS_Vmct.f19_g16.X.cheyenne_intel.GC.sept24
        /gpfs/u/home/dunlap/UFSCOMP.sept24/cime/src/components/xcpl_comps/xice/mct/ice_comp_mct.F90(5): error #5082: Syntax error, found ';' when expecting one of: => ( :
        
        /gpfs/u/home/dunlap/UFSCOMP.sept24/cime/src/components/xcpl_comps/xice/mct/ice_comp_mct.F90(53): error #6457: This derived type name has not been declared.   [ESMF_CLOCK]
        
        /gpfs/u/home/dunlap/UFSCOMP.sept24/cime/src/components/xcpl_comps/xice/mct/ice_comp_mct.F90(55): error #6457: This derived type name has not been declared.   [MCT_AVECT]
        
        /gpfs/u/home/dunlap/UFSCOMP.sept24/cime/src/components/xcpl_comps/xice/mct/ice_comp_mct.F90(60): error #6457: This derived type name has not been declared.   [MCT_GSMAP]
        
        /gpfs/u/home/dunlap/UFSCOMP.sept24/cime/src/components/xcpl_comps/xice/mct/ice_comp_mct.F90(61): error #6457: This derived type name has not been declared.   [MCT_GGRID]
        
        /gpfs/u/home/dunlap/UFSCOMP.sept24/cime/src/components/xcpl_comps/xice/mct/ice_comp_mct.F90(152): error #6457: This derived type name has not been declared.   [ESMF_CLOCK]
        
        /gpfs/u/home/dunlap/UFSCOMP.sept24/cime/src/components/xcpl_comps/xice/mct/ice_comp_mct.F90(154): error #6457: This derived type name has not been declared.   [MCT_AVECT]
        
        /gpfs/u/home/dunlap/UFSCOMP.sept24/cime/src/components/xcpl_comps/xice/mct/ice_comp_mct.F90(155): error #6457: This derived type name has not been declared.   [MCT_AVECT]
        
        /gpfs/u/home/dunlap/UFSCOMP.sept24/cime/src/components/xcpl_comps/xice/mct/ice_comp_mct.F90(159): error #6457: This derived type name has not been declared.   [MCT_GSMAP]
        
        /gpfs/u/home/dunlap/UFSCOMP.sept24/cime/src/components/xcpl_comps/xice/mct/ice_comp_mct.F90(160): error #6457: This derived type name has not been declared.   [MCT_GGRID]
        
        /gpfs/u/home/dunlap/UFSCOMP.sept24/cime/src/components/xcpl_comps/xice/mct/ice_comp_mct.F90(193): error #6457: This derived type name has not been declared.   [ESMF_CLOCK]
        
        /gpfs/u/home/dunlap/UFSCOMP.sept24/cime/src/components/xcpl_comps/xice/mct/ice_comp_mct.F90(195): error #6457: This derived type name has not been declared.   [MCT_AVECT]
        
        /gpfs/u/home/dunlap/UFSCOMP.sept24/cime/src/components/xcpl_comps/xice/mct/ice_comp_mct.F90(196): error #6457: This derived type name has not been declared.   [MCT_AVECT]
        
        /gpfs/u/home/dunlap/UFSCOMP.sept24/cime/src/components/xcpl_comps/xice/mct/ice_comp_mct.F90(77): error #6404: This name does not have a type, and must have an explicit type.   [GSMAP]
        
        /gpfs/u/home/dunlap/UFSCOMP.sept24/cime/src/components/xcpl_comps/xice/mct/ice_comp_mct.F90(78): error #6404: This name does not have a type, and must have an explicit type.   [GGRID]
        
        /gpfs/u/home/dunlap/UFSCOMP.sept24/cime/src/components/xcpl_comps/xice/mct/ice_comp_mct.F90(77): error #6691: A pointer dummy argument may only be argument associated with a pointer.   [GSMAP]
        
        /gpfs/u/home/dunlap/UFSCOMP.sept24/cime/src/components/xcpl_comps/xice/mct/ice_comp_mct.F90(78): error #6691: A pointer dummy argument may only be argument associated with a pointer.   [GGRID]
        
        /gpfs/u/home/dunlap/UFSCOMP.sept24/cime/src/components/xcpl_comps/xice/mct/ice_comp_mct.F90(114): error #6404: This name does not have a type, and must have an explicit type.   [ECLOCK]
        
        /gpfs/u/home/dunlap/UFSCOMP.sept24/cime/src/components/xcpl_comps/xice/mct/ice_comp_mct.F90(114): error #6404: This name does not have a type, and must have an explicit type.   [X2D]
        
        /gpfs/u/home/dunlap/UFSCOMP.sept24/cime/src/components/xcpl_comps/xice/mct/ice_comp_mct.F90(114): error #6404: This name does not have a type, and must have an explicit type.   [D2X]
        
        /gpfs/u/home/dunlap/UFSCOMP.sept24/cime/src/components/xcpl_comps/xice/mct/ice_comp_mct.F90(116): error #6691: A pointer dummy argument may only be argument associated with a pointer.   [GSMAP]
        
        /gpfs/u/home/dunlap/UFSCOMP.sept24/cime/src/components/xcpl_comps/xice/mct/ice_comp_mct.F90(116): error #6691: A pointer dummy argument may only be argument associated with a pointer.   [GGRID]
        
        /gpfs/u/home/dunlap/UFSCOMP.sept24/cime/src/components/xcpl_comps/xice/mct/ice_comp_mct.F90(172): error #6691: A pointer dummy argument may only be argument associated with a pointer.   [GSMAP]
        
        /gpfs/u/home/dunlap/UFSCOMP.sept24/cime/src/components/xcpl_comps/xice/mct/ice_comp_mct.F90(173): error #6691: A pointer dummy argument may only be argument associated with a pointer.   [GGRID]
        
        /gpfs/u/home/dunlap/UFSCOMP.sept24/cime/src/components/xcpl_comps/xice/mct/ice_comp_mct.F90(176): error #6404: This name does not have a type, and must have an explicit type.   [ECLOCK]
        
        /gpfs/u/home/dunlap/UFSCOMP.sept24/cime/src/components/xcpl_comps/xice/mct/ice_comp_mct.F90(176): error #6404: This name does not have a type, and must have an explicit type.   [X2D]
        
        /gpfs/u/home/dunlap/UFSCOMP.sept24/cime/src/components/xcpl_comps/xice/mct/ice_comp_mct.F90(176): error #6404: This name does not have a type, and must have an explicit type.   [D2X]
        
        /gpfs/u/home/dunlap/UFSCOMP.sept24/cime/src/components/xcpl_comps/xice/mct/ice_comp_mct.F90(177): error #6691: A pointer dummy argument may only be argument associated with a pointer.   [GSMAP]
        
        /gpfs/u/home/dunlap/UFSCOMP.sept24/cime/src/components/xcpl_comps/xice/mct/ice_comp_mct.F90(177): error #6691: A pointer dummy argument may only be argument associated with a pointer.   [GGRID]
        
        /gpfs/u/home/dunlap/UFSCOMP.sept24/cime/src/components/xcpl_comps/xice/mct/ice_comp_mct.F90(186): error #6404: This name does not have a type, and must have an explicit type.   [ECLOCK]
        
        ERROR: BUILD FAIL: buildexe failed, cat /glade/scratch/dunlap/SMS_Vmct.f19_g16.X.cheyenne_intel.GC.sept24/bld/cesm.bldlog.180924-103849
```

**Comment by rsdunlapiv** [comment]
```
    Case dir: /glade/scratch/dunlap/SMS_Vmct_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io.GC.sept24
    Errors were:
        Building test for SMS in directory /gpfs/fs1/scratch/dunlap/SMS_Vmct_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io.GC.sept24
        /gpfs/u/home/dunlap/UFSCOMP.sept24/components/cam/src/cpl/mct/atm_comp_mct.F90(207): error #6285: There is no matching specific subroutine for this generic subroutine call.   [SEQ_INFODATA_GETDATA]
        
        ERROR: BUILD FAIL: cam.buildlib failed, cat /glade/scratch/dunlap/SMS_Vmct_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io.GC.sept24/bld/atm.bldlog.180924-115929
```

**Comment by jedwards4b** [comment]
You still need to update cam
cam: nuopc_cap_n23_cam6_0_002

**Comment by rsdunlapiv** [comment]
```
    Case dir: /glade/scratch/dunlap/SMS_Vmct_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io.GC.sept24
    Errors were:
        Building test for SMS in directory /gpfs/fs1/scratch/dunlap/SMS_Vmct_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io.GC.sept24
        /gpfs/u/home/dunlap/UFSCOMP.sept24/cime/src/drivers/mct/main/cime_driver.F90(82): error #6404: This name does not have a type, and must have an explicit type.   [ESMF_VERSION_MAJOR]
        
        ERROR: BUILD FAIL: buildexe failed, cat /glade/scratch/dunlap/SMS_Vmct_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io.GC.sept24/bld/cesm.bldlog.180924-124300

```

**Comment by rsdunlapiv** [comment]
Test results:

```
dunlap@cheyenne1:/glade/scratch/dunlap> ./cs.status.sept24 | grep "FAIL " | grep -v NLCOMP
    FAIL ERR_Vmct_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io COMPARE_base_rest
    FAIL ERR_Vnuopc_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io COMPARE_base_rest
    FAIL ERS_Vmct_Ld5.T62_g16.CMOM.cheyenne_intel.mom-nuopc_cap COMPARE_base_rest
    FAIL ERS_Vmct_Ld5.T62_g16.GMOM.cheyenne_intel.mom-nuopc_cap COMPARE_base_rest
    FAIL ERS_Vmct_Ld5.T62_g37.DTEST.cheyenne_intel.cice-nuopc_cap BASELINE sept19: DIFF
    FAIL ERS_Vmct_Ln9.f19_g16.X.cheyenne_intel BASELINE sept19: DIFF
    FAIL ERS_Vmct_Ln9.T31_g37_rx1.A.cheyenne_intel BASELINE sept19: DIFF
    FAIL ERS_Vnuopc_Ld5.T62_g16.GMOM.cheyenne_intel.mom-nuopc_cap BASELINE exception
    FAIL ERS_Vnuopc_Ln9_N3.T31_g37_rx1.A.cheyenne_intel RUN time=38
    FAIL SMS_Vmct.f19_g16.X.cheyenne_intel BASELINE sept19: DIFF
    FAIL SMS_Vmct_Ld1.T31_g37_rx1.A.cheyenne_intel BASELINE sept19: DIFF
    FAIL SMS_Vmct_Ld5.T62_g16.GMOM.cheyenne_intel.mom-nuopc_cap MEMCOMP Error: Memory usage increase > 10% from baseline
    FAIL SMS_Vmct_Ld5.T62_g37.DTEST.cheyenne_intel.cice-nuopc_cap BASELINE sept19: DIFF
```

**Comment by jedwards4b** [comment]
@rsdunlapiv I've fixed ERS_Vnuopc_Ln9_N3.T31_g37_rx1.A.cheyenne_intel and the rest are expected.

**Comment by rsdunlapiv** [comment]
Test of ERS_Vnuopc_Ln9_N3.T31_g37_rx1.A.cheyenne_intel passed.
```/glade/scratch/dunlap/ERS_Vnuopc_Ln9_N3.T31_g37_rx1.A.cheyenne_intel.20180925_101613_w3ec8s```

**Pull request merged**
