### PR TITLE
major refactor and directory restructuring

### PR DESCRIPTION
**Pull request by mvertens**
major refactor and directory restructuring

- The following directory restructuring was done
  - shr/ -> mediator/
  - cime_flds -> mediator/
  - shr_cime_flds/ -> cime/src/share/nuopc/
- All mediator share code (e.g. shr_nuopc_methods_mod) is not ONLY being used by routines in mediator/ and cime_driver/
- Each external component (cam, clm, mom, etc) and cime components (data and xcpl ) now have their own ESMF/NUOPC share code - so they are completely independent of each other AND of the mediator share code
- There is no longer the file shr_scalar_mod - the scalar fields are now handled via the config attributes in each component
- The present flags are no longer set in the driver but in the mediator component
- All references to shr_abort_mod and shr_file_mod are gone

To checkout the correct externals:
> git clone  https://github.com/ESCOMP/UFSCOMP.git
> git checkout the tag cesm-cmeps-v0.8

The above will check out the relevant tags used for externals in this PR (except for CIME)

Test suite: testlist_drv.xml
Test baseline: /glade/scratch/jedwards/BASELINES/apr02 (**generated new apr16 baselines**)
Test namelist changes: 
Test status: bit for bit (except for X compset) - and all expected fails still there
Fixes: None
User interface changes?: No
Update gh-pages html (Y/N)?: No
Code review: 
****

### CODE REVIEW

**Review by jedwards4b — APPROVED** [review]

**Comment by rsdunlapiv** [comment]
@jedwards4b The build error I am now receiving:

```
dunlap@cheyenne6:/glade/scratch/dunlap/SMS_Vnuopc_Ld5.T62_g16.CMOM.cheyenne_intel.mom-nuopc_cap.C.20190416_130430_54yn6g/bld> tail  ocn.bldlog.190416-131305 
ar: creating libfms.a

Traceback (most recent call last):
  File "/gpfs/u/home/dunlap/UFSCOMP.apr16/components/mom//cime_config/buildlib", line 126, in <module>
    _main_func()
  File "/gpfs/u/home/dunlap/UFSCOMP.apr16/components/mom//cime_config/buildlib", line 121, in _main_func
    buildlib(caseroot, libroot, bldroot)
  File "/gpfs/u/home/dunlap/UFSCOMP.apr16/components/mom//cime_config/buildlib", line 51, in buildlib
    .format(cvmixdir, tlcvmix))
UnboundLocalError: local variable 'tlcvmix' referenced before assignment
```

**Comment by rsdunlapiv** [comment]
@mvertens and @uturuncoglu - I am getting a build error with this branch:

```
cat /glade/scratch/dunlap/SMS_Vnuopc_Ld3.f09_f09_mg17.A1850DLND.cheyenne_intel.C.20190422_120312_vn74qs/bld/cesm.bldlog.190422-120450

/gpfs/u/home/dunlap/UFSCOMP.apr16/cime/src/drivers/nuopc/mediator/med.F90(558): error #6404: This name does not have a type, and must have an explicit type.   [MASTERTASK]
    if (mastertask) then
--------^
/gpfs/u/home/dunlap/UFSCOMP.apr16/cime/src/drivers/nuopc/mediator/med.F90(558): error #6341: A logical data type is required in this context.   [MASTERTASK]
    if (mastertask) then
--------^
compilation aborted for /gpfs/u/home/dunlap/UFSCOMP.apr16/cime/src/drivers/nuopc/mediator/med.F90 (code 1)
gmake: *** [med.o] Error 1
```

**Comment by rsdunlapiv** [comment]
I added in the missing use statement and restarted the tests.

**Comment by rsdunlapiv** [comment]
@mvertens @uturuncoglu More compile errors:

```
cat /glade/scratch/dunlap/SMS_Vmct_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io.C.20190422_124105_fa6y1f/bld/csm_share.bldlog.190422-1

/gpfs/u/home/dunlap/UFSCOMP.apr16/cime/src/share/util/shr_cal_mod.F90(40): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [ESMF]
  use esmf
------^
/gpfs/u/home/dunlap/UFSCOMP.apr16/cime/src/share/util/shr_cal_mod.F90(237): error #6457: This derived type name has not been declared.   [ESMF_TIME]
    type(ESMF_Time),intent(out) :: etime
---------^
/gpfs/u/home/dunlap/UFSCOMP.apr16/cime/src/share/util/shr_cal_mod.F90(244): error #6457: This derived type name has not been declared.   [ESMF_CALKIND_FLAG]
    type(ESMF_CALKIND_FLAG) :: calkind
---------^
/gpfs/u/home/dunlap/UFSCOMP.apr16/cime/src/share/util/shr_cal_mod.F90(273): error #6457: This derived type name has not been declared.   [ESMF_TIME]
    type(ESMF_Time),intent(out) :: etime
---------^
/gpfs/u/home/dunlap/UFSCOMP.apr16/cime/src/share/util/shr_cal_mod.F90(281): error #6457: This derived type name has not been declared.   [ESMF_CALKIND_FLAG]
    type(ESMF_CALKIND_FLAG) :: calkind
---------^
/gpfs/u/home/dunlap/UFSCOMP.apr16/cime/src/share/util/shr_cal_mod.F90(327): error #6457: This derived type name has not been declared.   [ESMF_TIME]
    type(ESMF_time) :: time1,time2
---------^
/gpfs/u/home/dunlap/UFSCOMP.apr16/cime/src/share/util/shr_cal_mod.F90(328): error #6457: This derived type name has not been declared.   [ESMF_TIMEINTERVAL]
    type(ESMF_timeInterval) :: timeint
---------^
/gpfs/u/home/dunlap/UFSCOMP.apr16/cime/src/share/util/shr_cal_mod.F90(329): error #6457: This derived type name has not been declared.   [ESMF_CALKIND_FLAG]
    type(ESMF_CALKIND_FLAG) :: calkind
---------^
```

**Comment by rsdunlapiv** [comment]
The tests ran, but some of the baselines were missing.  I am regenerating baselines from the previous PR #86 and then I will resubmit these tests.

```
dunlap@cheyenne5:~/UFSCOMP.apr22intel19/cime/scripts> qcmd -l walltime=4:00:00 -- ./create_test --xml-testlist ../src/drivers/nuopc/cime_config/testdefs/testlist_drv.xml --generate apr22intel19 --baseline-root /glade/scratch/dunlap/BASELINES/ --xml-machine cheyenne
```

**Comment by rsdunlapiv** [comment]
Externals have been updated to be strictly versioned in UFSCOMP app_cesm-cmeps.
https://github.com/ESCOMP/UFSCOMP/commit/7299379339e29e95dce5c06d0ca19ab13683a2ac

**Pull request merged**
