### PR TITLE
Jedwards/ensembledriver2

### PR DESCRIPTION
**Pull request by jedwards4b**
Adds a top level ensemble driver, clean up dead models

Test suite: ./create_test --xml-testlist ./testlist_cmeps.xml --xml-machine cheyenne --xml-category prealpha --walltime 00:30:00 --compare aug28 --baseline-root /glade/scratch/dunlap/BASELINES 
Test baseline: aug28
Test namelist changes: 
Test status: bit for bit

Fixes 

User interface changes?: 

Update gh-pages html (Y/N)?:

Code review: 

Component states:
cam: nuopc_cap_n22_cam6_0_002
clm: c0c92b2
cice: dae5f518
mom:766f1b4
MOM: 9733d7d

### CODE REVIEW

**Comment by jedwards4b** [comment]
@rsdunlapiv This PR is ready for testing.

**Comment by rsdunlapiv** [comment]
@jedwards4b needs to push the changes to CICE.

Expecting hash:  `dae5f518`

but latest commit is:
```
commit 2f9c184cdc7dc1ff204e8e4f660d9e3fda3d4e8b
Author: Mariana Vertenstein <mvertens@ucar.edu>
Date:   Tue Sep 4 17:45:03 2018 -0600

    bug fix for grid specification
```

**Comment by rsdunlapiv** [comment]
Okay, using this fork instead:
git@github.com:jedwards4b/CESM_CICE5.git

**Comment by rsdunlapiv** [comment]
Started test suite:
```
dunlap@cheyenne3:~/UFSCOMP.sept17/cime/scripts> qcmd -l walltime=04:00:00 -- ./create_test --xml-machine cheyenne --xml-testlist testlist_cmeps.xml --baseline-root /glade/scratch/dunlap/BASELINES --compare aug28 --test-id sept17 --generate sept17
```

**Comment by rsdunlapiv** [comment]
Failures:

```
dunlap@cheyenne3:/glade/scratch/dunlap> ./cs.status.sept17  | grep "FAIL "
    FAIL ERR_Vmct_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io RUN time=188
    FAIL ERR_Vnuopc_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io NLCOMP
    FAIL ERR_Vnuopc_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io RUN time=350
    FAIL ERS_Vmct_Ld5.T62_g16.CMOM.cheyenne_intel.mom-nuopc_cap RUN time=234
    FAIL ERS_Vmct_Ld5.T62_g16.GMOM.cheyenne_intel.mom-nuopc_cap RUN time=257
    FAIL ERS_Vmct_Ln9.f19_g16.X.cheyenne_intel COMPARE_base_rest
    FAIL ERS_Vnuopc_Ld5.T62_g16.CMOM.cheyenne_intel.mom-nuopc_cap NLCOMP
    FAIL ERS_Vnuopc_Ld5.T62_g16.CMOM.cheyenne_intel.mom-nuopc_cap RUN time=449
    FAIL ERS_Vnuopc_Ld5.T62_g16.GMOM.cheyenne_intel.mom-nuopc_cap NLCOMP
    FAIL ERS_Vnuopc_Ld5.T62_g16.GMOM.cheyenne_intel.mom-nuopc_cap RUN time=371
    FAIL ERS_Vnuopc_Ld5.T62_g37.DTEST.cheyenne_intel.cice-nuopc_cap NLCOMP
    FAIL ERS_Vnuopc_Ln5.f19_g16.F2000Nuopc.cheyenne_intel.cam-nuopc_cap NLCOMP
    FAIL ERS_Vnuopc_Ln5.f19_g16.F2000Nuopc.cheyenne_intel.cam-nuopc_cap RUN time=24
    FAIL ERS_Vnuopc_Ln5.f45_f45_mg37.I2000Clm50SpNuopc.cheyenne_intel.clm-nuopc_cap NLCOMP
    FAIL ERS_Vnuopc_Ln5.ne16_ne16_mg17.QPC4.cheyenne_intel.cam-nuopc_cap NLCOMP
    FAIL ERS_Vnuopc_Ln9.f19_g16.X.cheyenne_intel NLCOMP
    FAIL ERS_Vnuopc_Ln9.T31_g37_rx1.A.cheyenne_intel NLCOMP
    FAIL SMS_Vmct_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io RUN time=187
    FAIL SMS_Vmct_Ld5.T62_g16.CMOM.cheyenne_intel.mom-nuopc_cap RUN time=244
    FAIL SMS_Vmct_Ld5.T62_g16.GMOM.cheyenne_intel.mom-nuopc_cap RUN time=270
    FAIL SMS_Vmct_Ld5.T62_g37.DTEST.cheyenne_intel.cice-nuopc_cap MEMCOMP Error: Memory usage increase > 10% from baseline
    FAIL SMS_Vnuopc.f19_g16.X.cheyenne_intel NLCOMP
    FAIL SMS_Vnuopc_Ld1.T31_g37_rx1.A.cheyenne_intel NLCOMP
    FAIL SMS_Vnuopc_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io NLCOMP
    FAIL SMS_Vnuopc_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io RUN time=349
    FAIL SMS_Vnuopc_Ld5.T62_g16.CMOM.cheyenne_intel.mom-nuopc_cap NLCOMP
    FAIL SMS_Vnuopc_Ld5.T62_g16.CMOM.cheyenne_intel.mom-nuopc_cap RUN time=443
    FAIL SMS_Vnuopc_Ld5.T62_g16.GMOM.cheyenne_intel.mom-nuopc_cap NLCOMP
    FAIL SMS_Vnuopc_Ld5.T62_g16.GMOM.cheyenne_intel.mom-nuopc_cap RUN time=369
    FAIL SMS_Vnuopc_Ld5.T62_g37.DTEST.cheyenne_intel.cice-nuopc_cap NLCOMP
    FAIL SMS_Vnuopc_Ln5.f19_g16.F2000Nuopc.cheyenne_intel.cam-nuopc_cap NLCOMP
    FAIL SMS_Vnuopc_Ln5.f19_g16.F2000Nuopc.cheyenne_intel.cam-nuopc_cap RUN time=26
    FAIL SMS_Vnuopc_Ln5.f45_f45_mg37.I2000Clm50SpNuopc.cheyenne_intel.clm-nuopc_cap NLCOMP
    FAIL SMS_Vnuopc_Ln5.ne16_ne16_mg17.QPC4.cheyenne_intel.cam-nuopc_cap NLCOMP
```

**Comment by rsdunlapiv** [comment]
Resubmitted tests with correct CIME branch merged in and latest CICE:
```dunlap@cheyenne3:~/UFSCOMP.sept17/cime/scripts> qcmd -l walltime=04:00:00 -- ./create_test --xml-machine cheyenne --xml-testlist testlist_cmeps.xml --baseline-root /glade/scratch/dunlap/BASELINES --compare aug28 --test-id sept17b --generate sept17 -o```

**Comment by rsdunlapiv** [comment]
Failures from last run:

```
dunlap@cheyenne4:/glade/scratch/dunlap> ./cs.status.sept17b | grep "FAIL " | grep -v NLCOMP
    FAIL ERR_Vmct_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io COMPARE_base_rest
    FAIL ERR_Vmct_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io BASELINE aug28
    FAIL ERR_Vnuopc_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io COMPARE_base_rest
    FAIL ERR_Vnuopc_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io BASELINE aug28
    FAIL ERS_Vmct_Ld5.T62_g16.CMOM.cheyenne_intel.mom-nuopc_cap COMPARE_base_rest
    FAIL ERS_Vmct_Ld5.T62_g16.CMOM.cheyenne_intel.mom-nuopc_cap BASELINE aug28
    FAIL ERS_Vmct_Ld5.T62_g16.GMOM.cheyenne_intel.mom-nuopc_cap COMPARE_base_rest
    FAIL ERS_Vmct_Ld5.T62_g16.GMOM.cheyenne_intel.mom-nuopc_cap BASELINE aug28
    FAIL ERS_Vmct_Ln9.f19_g16.X.cheyenne_intel COMPARE_base_rest
    FAIL ERS_Vnuopc_Ld5.T62_g16.CMOM.cheyenne_intel.mom-nuopc_cap COMPARE_base_rest
    FAIL ERS_Vnuopc_Ld5.T62_g16.CMOM.cheyenne_intel.mom-nuopc_cap BASELINE aug28
    FAIL ERS_Vnuopc_Ld5.T62_g16.GMOM.cheyenne_intel.mom-nuopc_cap COMPARE_base_rest
    FAIL ERS_Vnuopc_Ld5.T62_g16.GMOM.cheyenne_intel.mom-nuopc_cap BASELINE aug28
    FAIL ERS_Vnuopc_Ln5.ne16_ne16_mg17.QPC4.cheyenne_intel.cam-nuopc_cap RUN time=102
    FAIL ERS_Vnuopc_Ln9_N3.T31_g37_rx1.A.cheyenne_intel BASELINE aug28: ERROR BFAIL baseline directory '/glade/scratch/dunlap/BASELINES/aug28/ERS_Vnuopc_Ln9_N3.T31_g37_rx1.A.cheyenne_intel' does not exist
    FAIL SMS_Vmct_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io BASELINE aug28
    FAIL SMS_Vmct_Ld5.T62_g16.CMOM.cheyenne_intel.mom-nuopc_cap BASELINE aug28
    FAIL SMS_Vmct_Ld5.T62_g16.GMOM.cheyenne_intel.mom-nuopc_cap BASELINE aug28
    FAIL SMS_Vnuopc_Ld1_N3.T31_g37_rx1.A.cheyenne_intel BASELINE aug28: ERROR BFAIL baseline directory '/glade/scratch/dunlap/BASELINES/aug28/SMS_Vnuopc_Ld1_N3.T31_g37_rx1.A.cheyenne_intel' does not exist
    FAIL SMS_Vnuopc_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io BASELINE aug28
    FAIL SMS_Vnuopc_Ld5.T62_g16.CMOM.cheyenne_intel.mom-nuopc_cap BASELINE aug28
    FAIL SMS_Vnuopc_Ld5.T62_g16.GMOM.cheyenne_intel.mom-nuopc_cap BASELINE aug28
    FAIL SMS_Vnuopc_Ln5.ne16_ne16_mg17.QPC4.cheyenne_intel.cam-nuopc_cap RUN time=106
```

**Comment by jedwards4b** [comment]
I have fixed the issue with ne16_ne16_mg17.QPC4.cheyenne_intel.cam-nuopc_cap.  In the course of doing so I noticed that the aqua_planet flag was not being set correctly in cesm.runconfig and have added a fix for that.  This fix changes the baseline for this test and so a baseline failure is expected. 
I think that all of the other test failures are expected and ongoing.

**Comment by rsdunlapiv** [comment]
dunlap@cheyenne5:~/UFSCOMP.sept17/cime/scripts> qcmd -l walltime=04:00:00 -- ./create_test --xml-machine cheyenne --xml-testlist testlist_cmeps.xml --baseline-root /glade/scratch/dunlap/BASELINES --compare aug28 --generate sept19 --test-id sept19

**Comment by rsdunlapiv** [comment]
Restarted tests with latest MOM_interface to fix restart files.
```
dunlap@cheyenne5:~/UFSCOMP.sept17/cime/scripts> qcmd -l walltime=04:00:00 -- ./create_test --xml-machine cheyenne --xml-testlist testlist_cmeps.xml --baseline-root /glade/scratch/dunlap/BASELINES --compare aug28 --generate sept19 --test-id sept19b
```

**Comment by rsdunlapiv** [comment]
Failures are as expected:
```
dunlap@cheyenne4:/glade/scratch/dunlap> ./cs.status.sept19b | grep "FAIL " | grep -v NLCOMP
    FAIL ERR_Vmct_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io COMPARE_base_rest
    FAIL ERR_Vmct_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io BASELINE aug28
    FAIL ERR_Vnuopc_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io COMPARE_base_rest
    FAIL ERR_Vnuopc_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io BASELINE aug28
    FAIL ERS_Vmct_Ld5.T62_g16.CMOM.cheyenne_intel.mom-nuopc_cap COMPARE_base_rest
    FAIL ERS_Vmct_Ld5.T62_g16.CMOM.cheyenne_intel.mom-nuopc_cap BASELINE aug28
    FAIL ERS_Vmct_Ld5.T62_g16.GMOM.cheyenne_intel.mom-nuopc_cap COMPARE_base_rest
    FAIL ERS_Vmct_Ld5.T62_g16.GMOM.cheyenne_intel.mom-nuopc_cap BASELINE aug28
    FAIL ERS_Vmct_Ln9.f19_g16.X.cheyenne_intel COMPARE_base_rest
    FAIL ERS_Vnuopc_Ld5.T62_g16.CMOM.cheyenne_intel.mom-nuopc_cap BASELINE aug28
    FAIL ERS_Vnuopc_Ld5.T62_g16.GMOM.cheyenne_intel.mom-nuopc_cap BASELINE aug28
    FAIL ERS_Vnuopc_Ln5.ne16_ne16_mg17.QPC4.cheyenne_intel.cam-nuopc_cap BASELINE aug28
    FAIL ERS_Vnuopc_Ln9_N3.T31_g37_rx1.A.cheyenne_intel RUN time=33
    FAIL SMS_Vmct_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io BASELINE aug28
    FAIL SMS_Vmct_Ld5.T62_g16.CMOM.cheyenne_intel.mom-nuopc_cap BASELINE aug28
    FAIL SMS_Vmct_Ld5.T62_g16.GMOM.cheyenne_intel.mom-nuopc_cap BASELINE aug28
    FAIL SMS_Vmct_Ld5.T62_g37.DTEST.cheyenne_intel.cice-nuopc_cap MEMCOMP Error: Memory usage increase > 10% from baseline
    FAIL SMS_Vnuopc_Ld1_N3.T31_g37_rx1.A.cheyenne_intel BASELINE aug28: ERROR BFAIL baseline directory '/glade/scratch/dunlap/BASELINES/aug28/SMS_Vnuopc_Ld1_N3.T31_g37_rx1.A.cheyenne_intel' does not exist
    FAIL SMS_Vnuopc_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io BASELINE aug28
    FAIL SMS_Vnuopc_Ld5.T62_g16.CMOM.cheyenne_intel.mom-nuopc_cap BASELINE aug28
    FAIL SMS_Vnuopc_Ld5.T62_g16.GMOM.cheyenne_intel.mom-nuopc_cap BASELINE aug28
    FAIL SMS_Vnuopc_Ln5.ne16_ne16_mg17.QPC4.cheyenne_intel.cam-nuopc_cap BASELINE aug28
```

**Pull request merged**
