### PR TITLE
Jedwards/update esmf and logging2

### PR DESCRIPTION
**Pull request by jedwards4b**
Refactor namelist.py to be case-insensitive in the sense that it will accept input in any case but it
will produce output files using the case as defined in namelist_definition.xml.   This allows both fortran namelists (case insensitive) and esmf config files (case sensitive) to be parsed in the same way.    Fix issues with pylint and unit tests in python.    

Test suite: scripts_regression_tests.py A_RunUnitTests B_CheckCode, testlist_cmeps.xml
Test baseline: restart_cime5.6.8
Test namelist changes: namelist items are reordered 
Test status: bit for bit

Fixes 

User interface changes?: 

Update gh-pages html (Y/N)?:

Code review: dunlap

### CODE REVIEW

**Comment by jedwards4b** [comment]
@rsdunlapiv when you run tests on this please generate a new baseline - this will fix the issue with BMOM and will populate the baselines with med.log files.

**Comment by mvertens** [comment]
@jedwards4b - Thanks!

**Comment by rsdunlapiv** [comment]
Tests are running:
dunlap@cheyenne5:~/UFSCOMP.aug9/cime/scripts> qcmd -l walltime=04:00:00 -- ./create_test --xml-testlist ./testlist_cmeps.xml --xml-category prealpha --xml-machine cheyenne --test-id aug16b  --compare restart_cime5.6.8 --generate aug16 --baseline-root /glade/scratch/dunlap/BASELINES -o
Submitting command to PBS using account P93300606:
    ./create_test --xml-testlist ./testlist_cmeps.xml --xml-category prealpha --xml-machine cheyenne --test-id aug16b --compare restart_cime5.6.8 --generate aug16 --baseline-root /glade/scratch/dunlap/BASELINES -o

**Comment by rsdunlapiv** [comment]
@jedwards4b - please see baseline failures below, more than just BMOM:

dunlap@cheyenne5:/glade/scratch/dunlap> ./cs.status.aug16b | grep "FAIL "
    FAIL ERR_Vmct_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io COMPARE_base_rest
    FAIL ERR_Vnuopc_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io NLCOMP
    FAIL ERR_Vnuopc_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io RUN time=17
    FAIL ERS_Vmct_Ld5.T62_g16.CMOM.cheyenne_intel.mom-nuopc_cap COMPARE_base_rest
    FAIL ERS_Vmct_Ld5.T62_g16.GMOM.cheyenne_intel.mom-nuopc_cap COMPARE_base_rest
    FAIL ERS_Vmct_Ld5.T62_g16.GMOM.cheyenne_intel.mom-nuopc_cap BASELINE restart_cime5.6.8
    FAIL ERS_Vmct_Ln9.f19_g16.X.cheyenne_intel COMPARE_base_rest
    FAIL ERS_Vnuopc_Ld5.T62_g16.CMOM.cheyenne_intel.mom-nuopc_cap NLCOMP
    FAIL ERS_Vnuopc_Ld5.T62_g16.CMOM.cheyenne_intel.mom-nuopc_cap COMPARE_base_rest
    FAIL ERS_Vnuopc_Ld5.T62_g16.GMOM.cheyenne_intel.mom-nuopc_cap NLCOMP
    FAIL ERS_Vnuopc_Ld5.T62_g16.GMOM.cheyenne_intel.mom-nuopc_cap COMPARE_base_rest
    FAIL ERS_Vnuopc_Ld5.T62_g16.GMOM.cheyenne_intel.mom-nuopc_cap BASELINE restart_cime5.6.8
    FAIL ERS_Vnuopc_Ld5.T62_g37.DTEST.cheyenne_intel.cice-nuopc_cap NLCOMP
    FAIL ERS_Vnuopc_Ld5.T62_g37.DTEST.cheyenne_intel.cice-nuopc_cap COMPARE_base_rest
    FAIL ERS_Vnuopc_Ln5.f19_g16.F2000Nuopc.cheyenne_intel.cam-nuopc_cap NLCOMP
    FAIL ERS_Vnuopc_Ln5.f45_f45_mg37.I2000Clm50SpNuopc.cheyenne_intel.clm-nuopc_cap NLCOMP
    FAIL ERS_Vnuopc_Ln5.ne16_ne16_mg17.QPC4.cheyenne_intel.cam-nuopc_cap NLCOMP
    FAIL ERS_Vnuopc_Ln9.f19_g16.X.cheyenne_intel NLCOMP
    FAIL ERS_Vnuopc_Ln9.f19_g16.X.cheyenne_intel BASELINE restart_cime5.6.8
    FAIL ERS_Vnuopc_Ln9.T31_g37_rx1.A.cheyenne_intel NLCOMP
    FAIL SMS_Vnuopc.f19_g16.X.cheyenne_intel NLCOMP
    FAIL SMS_Vnuopc.f19_g16.X.cheyenne_intel BASELINE restart_cime5.6.8
    FAIL SMS_Vnuopc_Ld1.T31_g37_rx1.A.cheyenne_intel NLCOMP
    FAIL SMS_Vnuopc_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io NLCOMP
    FAIL SMS_Vnuopc_Ld5.T62_g16.CMOM.cheyenne_intel.mom-nuopc_cap NLCOMP
    FAIL SMS_Vnuopc_Ld5.T62_g16.GMOM.cheyenne_intel.mom-nuopc_cap NLCOMP
    FAIL SMS_Vnuopc_Ld5.T62_g37.DTEST.cheyenne_intel.cice-nuopc_cap NLCOMP
    FAIL SMS_Vnuopc_Ln5.f19_g16.F2000Nuopc.cheyenne_intel.cam-nuopc_cap NLCOMP
    FAIL SMS_Vnuopc_Ln5.f45_f45_mg37.I2000Clm50SpNuopc.cheyenne_intel.clm-nuopc_cap NLCOMP
    FAIL SMS_Vnuopc_Ln5.ne16_ne16_mg17.QPC4.cheyenne_intel.cam-nuopc_cap NLCOMP

**Comment by jedwards4b** [comment]
I think you failed to update the cam component - you need nuopc_cap_n17_cam6_0_002

**Comment by rsdunlapiv** [comment]
That's the CAM tag I was using:

```
Checking status of externals: clm, fates, ptclm, mosart, cvmix, cime, cice, fms, fms, mom, mom, geokdtree, da_hooks, cam, 
s   ./cime
        clean sandbox, nuopc-cmeps --> origin/nuopc-cmeps
    ./components/cam
        clean sandbox, on cam1/branch_tags/nuopc_cap_tags/nuopc_cap_n17_cam6_0_002/components/cam
    ./components/cice
        clean sandbox, on 5fd959ea17fe62d1f805ddb60698c65d405bbd76
    ./components/clm
        clean sandbox, on f36db6b6d4038eb9a87ee6bf1c1c16b0a71957a8
    ./components/clm/src/fates
        clean sandbox, on fates_s1.8.1_a3.0.0
    ./components/clm/tools/PTCLM
        clean sandbox, on PTCLM2_180214
    ./components/mom
        clean sandbox, on 837470f1e4cc95605fd57acd00c2c3149fd7a2e8
    ./components/mom/MOM6
        clean sandbox, on 8fd077b35cc3e5fbc652a876feab81e351437899
    ./components/mom/MOM6/pkg/MOM6_DA_hooks
        clean sandbox, on 6d8834ca8cf399f1a0d202239d72919907f6cd74
    ./components/mom/MOM6/pkg/geoKdTree
        clean sandbox, on a4670b9743c883d310d821eeac5b1f77f587b9d5
    ./components/mosart
        clean sandbox, on 88e81bd6ba6f69fc7541f81be903d4b2f2293540
    ./libraries/CVMix
        clean sandbox, on v0.92-beta
    ./libraries/FMS
        clean sandbox, on 4a198e65401ba605e0fc44d1a2c0f4c9166dd6b4
    ./libraries/FMS/src
        clean sandbox, on warsaw_201803
```

**Comment by jedwards4b** [comment]
Sorry I meant nuopc_cap_n18_cam6_0_002

**Comment by rsdunlapiv** [comment]
Updated CAM tag and kicked off tests:

```
dunlap@cheyenne4:~/UFSCOMP.aug9/cime/scripts> qcmd -l walltime=04:00:00 -- ./create_test --xml-testlist ./testlist_cmeps.xml --xml-category prealpha --xml-machine cheyenne --test-id aug16late --compare restart_cime5.6.8 --generate aug16late --baseline-root /glade/scratch/dunlap/BASELINES -o
Submitting command to PBS using account P93300606:
    ./create_test --xml-testlist ./testlist_cmeps.xml --xml-category prealpha --xml-machine cheyenne --test-id aug16late --compare restart_cime5.6.8 --generate aug16late --baseline-root /glade/scratch/dunlap/BASELINES -o
```

**Comment by rsdunlapiv** [comment]
Results with the new CAM tag:

```
dunlap@cheyenne5:/glade/scratch/dunlap> ./cs.status.aug16late | grep "FAIL "
    FAIL ERR_Vmct_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io COMPARE_base_rest
    FAIL ERR_Vnuopc_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io NLCOMP
    FAIL ERR_Vnuopc_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io COMPARE_base_rest
    FAIL ERS_Vmct_Ld5.T62_g16.CMOM.cheyenne_intel.mom-nuopc_cap COMPARE_base_rest
    FAIL ERS_Vmct_Ld5.T62_g16.GMOM.cheyenne_intel.mom-nuopc_cap COMPARE_base_rest
    FAIL ERS_Vmct_Ld5.T62_g16.GMOM.cheyenne_intel.mom-nuopc_cap BASELINE restart_cime5.6.8
    FAIL ERS_Vmct_Ln9.f19_g16.X.cheyenne_intel COMPARE_base_rest
    FAIL ERS_Vnuopc_Ld5.T62_g16.CMOM.cheyenne_intel.mom-nuopc_cap NLCOMP
    FAIL ERS_Vnuopc_Ld5.T62_g16.CMOM.cheyenne_intel.mom-nuopc_cap COMPARE_base_rest
    FAIL ERS_Vnuopc_Ld5.T62_g16.GMOM.cheyenne_intel.mom-nuopc_cap NLCOMP
    FAIL ERS_Vnuopc_Ld5.T62_g16.GMOM.cheyenne_intel.mom-nuopc_cap COMPARE_base_rest
    FAIL ERS_Vnuopc_Ld5.T62_g16.GMOM.cheyenne_intel.mom-nuopc_cap BASELINE restart_cime5.6.8
    FAIL ERS_Vnuopc_Ld5.T62_g37.DTEST.cheyenne_intel.cice-nuopc_cap NLCOMP
    FAIL ERS_Vnuopc_Ld5.T62_g37.DTEST.cheyenne_intel.cice-nuopc_cap COMPARE_base_rest
    FAIL ERS_Vnuopc_Ln5.f19_g16.F2000Nuopc.cheyenne_intel.cam-nuopc_cap NLCOMP
    FAIL ERS_Vnuopc_Ln5.f45_f45_mg37.I2000Clm50SpNuopc.cheyenne_intel.clm-nuopc_cap NLCOMP
    FAIL ERS_Vnuopc_Ln5.ne16_ne16_mg17.QPC4.cheyenne_intel.cam-nuopc_cap NLCOMP
    FAIL ERS_Vnuopc_Ln9.f19_g16.X.cheyenne_intel NLCOMP
    FAIL ERS_Vnuopc_Ln9.f19_g16.X.cheyenne_intel BASELINE restart_cime5.6.8
    FAIL ERS_Vnuopc_Ln9.T31_g37_rx1.A.cheyenne_intel NLCOMP
    FAIL SMS_Vnuopc.f19_g16.X.cheyenne_intel NLCOMP
    FAIL SMS_Vnuopc.f19_g16.X.cheyenne_intel BASELINE restart_cime5.6.8
    FAIL SMS_Vnuopc_Ld1.T31_g37_rx1.A.cheyenne_intel NLCOMP
    FAIL SMS_Vnuopc_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io NLCOMP
    FAIL SMS_Vnuopc_Ld5.T62_g16.CMOM.cheyenne_intel.mom-nuopc_cap NLCOMP
    FAIL SMS_Vnuopc_Ld5.T62_g16.GMOM.cheyenne_intel.mom-nuopc_cap NLCOMP
    FAIL SMS_Vnuopc_Ld5.T62_g37.DTEST.cheyenne_intel.cice-nuopc_cap NLCOMP
    FAIL SMS_Vnuopc_Ln5.f19_g16.F2000Nuopc.cheyenne_intel.cam-nuopc_cap NLCOMP
    FAIL SMS_Vnuopc_Ln5.f45_f45_mg37.I2000Clm50SpNuopc.cheyenne_intel.clm-nuopc_cap NLCOMP
    FAIL SMS_Vnuopc_Ln5.ne16_ne16_mg17.QPC4.cheyenne_intel.cam-nuopc_cap NLCOMP
```

**Comment by rsdunlapiv** [comment]
Results and failures are consistent with what Mariana got, so merging this in.

**Pull request merged**
