### PR TITLE
new run sequence generation

### PR DESCRIPTION
**Pull request by mvertens**
This PR introduces new python scripts in cime_config/runseq to generate run sequences more flexibly

Test suite: testlist_drv.xml
Test baseline: may17intel19
Test namelist changes: yes (namelists are different due to removal of comments in run sequences, etc)
Test status: bit for bit
Fixes:None
User interface changes?: No
Update gh-pages html (Y/N)?:N
Code review: jedwards

### CODE REVIEW

**Comment by uturuncoglu** [comment]
@mvertens I am testing the PR but Travis CI checks are failed and i think that those are mainly related with the change in the run sequence files. Do you think that it can be fixed easily?

**Review by jedwards4b — APPROVED** [review]
brilliant!

**Comment by jedwards4b** [comment]
All of these new files fail the pylint check, you may need to add some pylint exceptions in the code.

**Comment by uturuncoglu** [comment]
You mean Python codes that is used to generate run sequences.

**Comment by uturuncoglu** [comment]
Okay. I am planing to create new baseline and then merge.

**Comment by mvertens** [comment]
@jedwards4b - thanks for fixing the pylint errors!

**Comment by uturuncoglu** [comment]
new baseline may23intel19 is created.

**Pull request merged**
