### PR TITLE
add restart capability and cleanup

### PR DESCRIPTION
**Pull request by mvertens**
add  mediator restart capability and update to cime5.6.8

Also update clocks, alarms, and filenames for consistency. med
history and restarts are set by the _OPTION and _N settings in
env_run.xml.

The model advance setRunClock has been specialized so it syncs with
the driver clock, advances one coupling period (to trigger alarms), then
resets the clock to the start of the coupling period. The clock is officially
advanced by the generic NUOPC AdvanceClock method.

The filenames are named based on the stop time of the current
coupling period. This should be done consistently in all components.
This has only been modified and validated with data models. Dead
models do not write history or restart files, so there is not a problem.
But prognostic models will probably need to have their caps setup
the same way.

med_phases_restart_write was added to the run sequence and
med_phases_history was renamed to med_phases_history_write.

Added ability to have driver restarts separate from mediator restarts
in the attributes. Current, the driver uses the mediator restarts.
Updated how the driver reads in the restart time. (The mediator
writes that time).

Updated use of "currentymd, currenttod" when it is really was
"nextymd, nexttod". also use "target_ymd, target_tod" in run method
to provide further clarification.

Logic associated with checking rpointer file and restart files in the
data models was improved.

Removed some excessive print statements.

Updated implementation associated with checking restart alarms in
components.

**TESTING NOTE:**
A new branch, `mvertens/app_cesm-cmeps`,  was created in https://github.com/ESCOMP/UFSCOMP.git that migrated the nuopc caps to the git versions of CICE, CTSM, MOSART and a recent version of the svn trunk of CAM. As a result, the comparisons to the baselines with these prognostic components will not be bfb.
New baselines were created for the tests in testlist_cmeps.xml in /glade/scratch/mvertens/BASELINES.

Test suite: testlist_cmeps.xml 
Test baseline: no
Test namelist changes: no
Test status: not bfb

Fixes [CIME Github issue #] #5

User interface changes?: N

Update gh-pages html (Y/N)?: N

Code review:

### CODE REVIEW

**Review by jedwards4b — APPROVED** [review]
I think that it would be better in the future to do rebases in a separate PR than changes to code so that we understand what is a merge change and what is new code.

**Comment by mvertens** [comment]
I completely agree. Sorry that so much got put into this at once.

**Comment by rsdunlapiv** [comment]
Comparing against @mvertens  new baselines - the files are there but CIME says it cannot find the counterpart file in my run directory.  
 
File '/glade/scratch/mvertens/BASELINES/restart_cime5.6.8/SMS_Vmct_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io/mom6.frc._0001_001.nc' had no counterpart in '/glade/scrat
ch/dunlap/SMS_Vmct_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io.C.restart_cime568/run' with suffix ''
    File '/glade/scratch/mvertens/BASELINES/restart_cime5.6.8/SMS_Vmct_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io/mom6.hmz._0001_006.nc' had no counterpart in '/glade/scrat
ch/dunlap/SMS_Vmct_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io.C.restart_cime568/run' with suffix ''
    File '/glade/scratch/mvertens/BASELINES/restart_cime5.6.8/SMS_Vmct_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io/mom6.prog._0001_006.nc' had no counterpart in '/glade/scra
tch/dunlap/SMS_Vmct_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io.C.restart_cime568/run' with suffix ''
    File '/glade/scratch/mvertens/BASELINES/restart_cime5.6.8/SMS_Vmct_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io/mom6.sfc.day._0001_001.nc' had no counterpart in '/glade/s
cratch/dunlap/SMS_Vmct_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io.C.restart_cime568/run' with suffix ''
    File '/glade/scratch/mvertens/BASELINES/restart_cime5.6.8/SMS_Vmct_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io/mom6.static.nc' had no counterpart in '/glade/scratch/dunl
ap/SMS_Vmct_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io.C.restart_cime568/run' with suffix ''

@jedwards4b  previously committed a fix for this and it's included in the restart_cime5.6.8 branch, but for some reason this is still an issue.
https://github.com/ESMCI/cmeps-cime/commit/3093688aefef4bfddd4ee6aa75514e657852c9a9

**Comment by jedwards4b** [comment]
I am working on a general fix for this in cime master https://github.com/ESMCI/cime/issues/2695, once I have it working there I can merge to this branch - can you wait?

**Comment by rsdunlapiv** [comment]
Sounds good, thanks @jedwards4b !

**Comment by jedwards4b** [comment]
@rsdunlapiv I've pushed a fix to this branch, please try again.

**Comment by rsdunlapiv** [comment]
@jedwards4b latest commit fixed most of the missing file issues, but the DTEST baseline still fails:

2018-07-25 14:55:52: Comparing hists for case 'SMS_Vnuopc_Ld5.T62_g37.DTEST.cheyenne_intel.cice-nuopc_cap.C.restart_cime568b' dir1='/glade/scratch/dunlap/SMS_Vnuopc_Ld5.T62_g37.DTEST.cheyenne_intel.cice-nuopc_
cap.C.restart_cime568b/run', suffix1='',  dir2='/glade/scratch/mvertens/BASELINES/restart_cime5.6.8/SMS_Vnuopc_Ld5.T62_g37.DTEST.cheyenne_intel.cice-nuopc_cap' suffix2=''
  comparing model 'datm'
    no hist files found for model datm
  comparing model 'slnd'
    no hist files found for model slnd
  comparing model 'cice'
    **File '/glade/scratch/dunlap/SMS_Vnuopc_Ld5.T62_g37.DTEST.cheyenne_intel.cice-nuopc_cap.C.restart_cime568b/run/SMS_Vnuopc_Ld5.T62_g37.DTEST.cheyenne_intel.cice-nuopc_cap.C.restart_cime568b.cice.h_inst.0001-
01-06-00000.nc' had no counterpart in '/glade/scratch/mvertens/BASELINES/restart_cime5.6.8/SMS_Vnuopc_Ld5.T62_g37.DTEST.cheyenne_intel.cice-nuopc_cap' with suffix ''**
  comparing model 'docn'
    no hist files found for model docn
  comparing model 'drof'
    no hist files found for model drof
  comparing model 'sglc'
    no hist files found for model sglc
  comparing model 'swav'
    no hist files found for model swav
  comparing model 'cpl'
    /glade/scratch/dunlap/SMS_Vnuopc_Ld5.T62_g37.DTEST.cheyenne_intel.cice-nuopc_cap.C.restart_cime568b/run/SMS_Vnuopc_Ld5.T62_g37.DTEST.cheyenne_intel.cice-nuopc_cap.C.restart_cime568b.cpl.hi.0001-01-06-00000
.nc matched /glade/scratch/mvertens/BASELINES/restart_cime5.6.8/SMS_Vnuopc_Ld5.T62_g37.DTEST.cheyenne_intel.cice-nuopc_cap/cpl.hi.0001-01-06-00000.nc

**Review by rsdunlapiv — APPROVED** [review]

**Comment by rsdunlapiv** [comment]
Going to accept this now - the DTEST baseline failure is because the changes from Jim require re-running the baseline.  No need to go through that process now.

**Pull request merged**
