### PR TITLE
new creation of nuopc.runseq

### PR DESCRIPTION
**Pull request by mvertens**
new creation of nuopc.runseq

This PR removes the creation of nuopc.runseq from the namelist_definition_drv.xml file.
For now it introduces a small number of new noupc_runseq_XXX files for different compset scenarios.
It is not expected that many more files will be needed to cover the CESM requirements. If we want to move to a more xml-based or yaml-based approach the current files would be a starting point. However, after a lot of thinking about this - I'm not convinced that this would provide a lot of benefit. The current files provide developers the ability to easily see what run sequences are available and a very simple method to add a new run sequence. 

**New capability.** For a user-created run sequence for a case, the user need only create a copy of nuopc.runseq in their caseroot directly and that one will be used instead.

All externals stay the same.

Test suite: testlist_drv.xml
Test baseline: jan24 from /glade/scratch/dunlap/BASELINES
Test namelist changes: no
Test status: bit for bit 
     namelists compare fail  due to removal of the runseq configuration from  namelist_definition_drv.xml)
Fixes: None
User interface changes?: no
Update gh-pages html (Y/N)?:no
Code review:

### CODE REVIEW

**Comment by rsdunlapiv** [comment]
@mvertens When I try this with the fv3 compset, it does not copy over the run sequence that I would expect.  See /glade/scratch/dunlap/fv3gfs.tony4/run

This is the run sequence it pulls in:
```
runSeq::
@1800   #ocean coupling step
    MED med_phases_prep_ocn_accum_avg
    MED med_connectors_prep_med2ocn
    MED -> OCN :remapMethod=redist
    @1800   # atmosphere coupling step
      MED med_phases_prep_ocn_map
      MED med_phases_aofluxes_run
      MED med_phases_prep_ocn_merge
      MED med_phases_prep_ocn_accum_fast
      MED med_phases_ocnalb_run
      MED med_phases_prep_lnd
      MED med_connectors_prep_med2lnd
      MED -> LND :remapMethod=redist
      MED med_phases_prep_ice
      MED med_connectors_prep_med2ice
      MED -> ICE :remapMethod=redist
      MED med_phases_prep_wav
      MED med_connectors_prep_med2wav
      MED -> WAV :remapMethod=redist
      MED med_phases_prep_rof
      MED med_connectors_prep_med2rof
      MED -> ROF :remapMethod=redist
      ICE
      LND
      ROF
      WAV
      ICE -> MED :remapMethod=redist
      MED med_connectors_post_ice2med
      MED med_fraction_set
      LND -> MED :remapMethod=redist
      MED med_connectors_post_lnd2med
      ROF -> MED :remapMethod=redist
      MED med_connectors_post_rof2med
      MED med_phases_prep_glc
      MED med_connectors_prep_med2glc
      MED -> GLC :remapMethod=redist
      MED med_phases_prep_atm
      MED med_connectors_prep_med2atm
      MED -> ATM :remapMethod=redist
      ATM
      GLC
      WAV -> MED :remapMethod=redist
      MED med_connectors_post_wav2med
      GLC -> MED :remapMethod=redist
      MED med_connectors_post_glc2med
      ATM -> MED :remapMethod=redist
      MED med_connectors_post_atm2med
      MED med_phases_history_write
      MED med_phases_profile
    @
    OCN
    OCN -> MED :remapMethod=redist
    MED med_connectors_post_ocn2med
    MED med_phases_restart_write
@

```

**Comment by rsdunlapiv** [comment]
@mvertens I just committed a fix, so should be okay

**Comment by mvertens** [comment]
sorry about that. Thanks for fixing it.

**Comment by mvertens** [comment]
I am really confused - since when I ran this I got the right file. At any
rate - I'm glad its resolved.

**Comment by rsdunlapiv** [comment]
Sure, no problem.  Keep an eye on your next run just to be 100% sure, but
my tests show that it gets the right run seq now, so I think we are good.

**Pull request merged**
