### PR TITLE
Jedwards/pelayout

### PR DESCRIPTION
**Pull request by jedwards4b**
Moves the pe configuration and layout tasks from mct to esmf.   We still need to set mct values but we now initialize using esmf and set values in mct instead of the other way around. 

Test suite: qcmd -l walltime=04:00:00 -- ./create_test --xml-machine cheyenne --xml-testlist testlist_cmeps.xml --baseline-root /glade/scratch/dunlap/BASELINES --compare sept24 
Test baseline: sept24
Test namelist changes: 
Test status: bit for bit
Fixes [CIME Github issue #]

User interface changes?: 

Update gh-pages html (Y/N)?:

Code review:

### CODE REVIEW

**Comment by jedwards4b** [comment]
The test SMS_Vnuopc_Ln5.f45_f45_mg37.I2000Clm50SpNuopc.cheyenne_intel.clm-nuopc_cap is failing.

**Comment by jedwards4b** [comment]
@rsdunlapiv ready

**Comment by jedwards4b** [comment]
@rsdunlapiv please generate new baselines

**Comment by rsdunlapiv** [comment]
@jedwards4b can you please send the list of hashes for each of the components?

**Comment by jedwards4b** [comment]
cime: 23cc3d578
cam: nuopc_cap_n23_cam6_0_002
cice: d772fff
clm: ce1e370
mosart: d8210ddb
mom_interface: 4b1b8b
MOM: 4b1b8b

**Comment by rsdunlapiv** [comment]
@jedwards4b Should MOM6 be 9733d7?  Also, I cannot find the cice hash - can you please confirm if you need to push?

**Comment by rsdunlapiv** [comment]
Failures are as expected:

```
dunlap@cheyenne1:/glade/scratch/dunlap> ./cs.status.20181005_142256_q5lh7o | grep "FAIL " | grep -v NLCOMP
    FAIL ERR_Vmct_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io COMPARE_base_rest
    FAIL ERR_Vnuopc_Ld5.f19_g16.BMOM.cheyenne_intel.allactive-nuopc_cap_io COMPARE_base_rest
    FAIL ERS_Vmct_Ld5.T62_g16.CMOM.cheyenne_intel.mom-nuopc_cap COMPARE_base_rest
    FAIL ERS_Vmct_Ld5.T62_g16.GMOM.cheyenne_intel.mom-nuopc_cap COMPARE_base_rest
    FAIL ERS_Vnuopc_Ln9_N3.T31_g37_rx1.A.cheyenne_intel BASELINE sept24: ERROR BFAIL some baseline files were missing
    FAIL SMS_Vmct_Ld5.T62_g16.CMOM.cheyenne_intel.mom-nuopc_cap MEMCOMP Error: Memory usage increase > 10% from baseline
```

**Comment by rsdunlapiv** [comment]
```
dunlap@cheyenne1:~/UFSCOMP.oct17/cime/scripts> qcmd -l walltime=04:00:00 -- ./create_test --xml-machine cheyenne --xml-testlist testlist_cmeps.xml --baseline-root /glade/scratch/dunlap/BASELINES --compare oct5
```

**Pull request merged**
